name: pipeline

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.7

  # Core bioinformatics tools
  - porechop
  - seqkit
  - filtlong
  - flye
  - minimap2
  - racon
  - fastqc
  - prokka
  - quast

  # Runtime
  - pip

  # Python app dependencies
  - pip:
      - Flask
      - Flask-Session
      - python-dotenv
      - requests
      - waitress
