name: pipeline

channels:
  - conda-forge
  - bioconda

dependencies:
  # Python (MUST be pinned)
  - python=3.10

  # Core bioinformatics tools
  - porechop
  - seqkit
  - filtlong
  - flye
  - minimap2
  - racon
  - fastqc
  - prokka
  - quast=5.2.0

  - matplotlib
  - joblib

  # Pip runtime
  - pip

  # Python app dependencies (pip)
  - pip:
      - Flask
      - Flask-Session
      - python-dotenv
      - requests
      - waitress
      - openai
      - mysql-connector-python
      - psutil
